### ISSUE TITLE
Michaljazfg READ PLZZZ

### ISSUE THREAD

**Issue by AriGham** [DevsySpodZabki/ObywatelPlus#24]
Hi I found ur Web Mc project but noticed that you haven't edited it in about a year. I tried it but would keep trying to connect to the server 144.24.169.18:25565 and when I tried changing that to something like the IP to pvp legacy, it would say that I need to sign in, but when I reloaded the page it wouldn't let me sign in and would keep sending me to 144.24.169.18:25565 again. Also, I don't understand how to use the offline mode. If you could put a comment here, that would be really helpful. Thank you! (P.S. if ur ReferTV, can u try contacting Michalijazfg? thx.)

**Comment by ReferTV** [comment]
ok, I passed on, however, this is not the place to report such things

**Comment by AriGham** [comment]
Sorry, I just wanted to get to Michaljazfg and I can't access discord right now. Thx for passing it on and sorry again for posting it here.

**Comment by ReferTV** [comment]
it's all right
